// tslint:disable
export const instruments = [
  {
    "figi": "BBG0013J12N1",
    "ticker": "TRYRUB_TOM",
    "classCode": "CETS",
    "isin": "",
    "lot": 1000,
    "currency": "rub",
    "klong": {
      "units": 2,
      "nano": 0
    },
    "kshort": {
      "units": 2,
      "nano": 0
    },
    "dlong": {
      "units": 0,
      "nano": 991900000
    },
    "dshort": {
      "units": 2,
      "nano": 648100000
    },
    "dlongMin": {
      "units": 0,
      "nano": 910000000
    },
    "dshortMin": {
      "units": 0,
      "nano": 910000000
    },
    "shortEnabledFlag": false,
    "name": "Турецкая лира",
    "exchange": "FX",
    "nominal": {
      "currency": "try",
      "units": 1,
      "nano": 0
    },
    "countryOfRisk": "",
    "countryOfRiskName": "",
    "tradingStatus": 1,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "isoCurrencyName": "try",
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG000VJ5YR4",
    "ticker": "GLDRUB_TOM",
    "classCode": "CETS",
    "isin": "",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "Золото",
    "exchange": "FX_MTL",
    "nominal": {
      "currency": "xau",
      "units": 1,
      "nano": 0
    },
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "tradingStatus": 1,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "isoCurrencyName": "xau",
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": false,
    "uid": ""
  },
  {
    "figi": "BBG000VHQTD1",
    "ticker": "SLVRUB_TOM",
    "classCode": "CETS",
    "isin": "",
    "lot": 100,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "Серебро",
    "exchange": "FX_MTL",
    "nominal": {
      "currency": "xag",
      "units": 1,
      "nano": 0
    },
    "countryOfRisk": "",
    "countryOfRiskName": "",
    "tradingStatus": 1,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "isoCurrencyName": "xag",
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": false,
    "uid": ""
  },
  {
    "figi": "BBG0013HJJ31",
    "ticker": "EUR_RUB__TOM",
    "classCode": "CETS",
    "isin": "",
    "lot": 1000,
    "currency": "rub",
    "klong": {
      "units": 2,
      "nano": 0
    },
    "kshort": {
      "units": 2,
      "nano": 0
    },
    "dlong": {
      "units": 0,
      "nano": 250000000
    },
    "dshort": {
      "units": 0,
      "nano": 250000000
    },
    "dlongMin": {
      "units": 0,
      "nano": 134000000
    },
    "dshortMin": {
      "units": 0,
      "nano": 118000000
    },
    "shortEnabledFlag": true,
    "name": "Евро",
    "exchange": "FX",
    "nominal": {
      "currency": "eur",
      "units": 1,
      "nano": 0
    },
    "countryOfRisk": "",
    "countryOfRiskName": "",
    "tradingStatus": 1,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "isoCurrencyName": "eur",
    "minPriceIncrement": {
      "units": 0,
      "nano": 2500000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG0013HG026",
    "ticker": "KZTRUB_TOM",
    "classCode": "CETS",
    "isin": "",
    "lot": 10000,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "Тенге",
    "exchange": "FX",
    "nominal": {
      "currency": "kzt",
      "units": 100,
      "nano": 0
    },
    "countryOfRisk": "",
    "countryOfRiskName": "",
    "tradingStatus": 1,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "isoCurrencyName": "kzt",
    "minPriceIncrement": {
      "units": 0,
      "nano": 2500000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG00D87WQY7",
    "ticker": "BYNRUB_TOM",
    "classCode": "CETS",
    "isin": "",
    "lot": 1000,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "Белорусский рубль",
    "exchange": "FX",
    "nominal": {
      "currency": "byn",
      "units": 1,
      "nano": 0
    },
    "countryOfRisk": "",
    "countryOfRiskName": "",
    "tradingStatus": 1,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "isoCurrencyName": "byn",
    "minPriceIncrement": {
      "units": 0,
      "nano": 2500000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG0013HSW87",
    "ticker": "HKDRUB_TOM",
    "classCode": "CETS",
    "isin": "HKDRUB__CETS",
    "lot": 1000,
    "currency": "rub",
    "klong": {
      "units": 2,
      "nano": 0
    },
    "kshort": {
      "units": 2,
      "nano": 0
    },
    "dlong": {
      "units": 0,
      "nano": 991900000
    },
    "dshort": {
      "units": 2,
      "nano": 648100000
    },
    "dlongMin": {
      "units": 0,
      "nano": 910000000
    },
    "dshortMin": {
      "units": 0,
      "nano": 910000000
    },
    "shortEnabledFlag": false,
    "name": "Гонконгский доллар",
    "exchange": "FX",
    "nominal": {
      "currency": "hkd",
      "units": 1,
      "nano": 0
    },
    "countryOfRisk": "",
    "countryOfRiskName": "",
    "tradingStatus": 1,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "isoCurrencyName": "hkd",
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG0013HRTL0",
    "ticker": "CNYRUB_TOM",
    "classCode": "CETS",
    "isin": "",
    "lot": 1000,
    "currency": "rub",
    "klong": {
      "units": 2,
      "nano": 0
    },
    "kshort": {
      "units": 2,
      "nano": 0
    },
    "dlong": {
      "units": 0,
      "nano": 991900000
    },
    "dshort": {
      "units": 2,
      "nano": 648100000
    },
    "dlongMin": {
      "units": 0,
      "nano": 910000000
    },
    "dshortMin": {
      "units": 0,
      "nano": 910000000
    },
    "shortEnabledFlag": false,
    "name": "Юань",
    "exchange": "FX",
    "nominal": {
      "currency": "cny",
      "units": 1,
      "nano": 0
    },
    "countryOfRisk": "",
    "countryOfRiskName": "",
    "tradingStatus": 1,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "isoCurrencyName": "cny",
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG0013HGFT4",
    "ticker": "USD000UTSTOM",
    "classCode": "CETS",
    "isin": "",
    "lot": 1000,
    "currency": "rub",
    "klong": {
      "units": 2,
      "nano": 0
    },
    "kshort": {
      "units": 2,
      "nano": 0
    },
    "dlong": {
      "units": 0,
      "nano": 250000000
    },
    "dshort": {
      "units": 0,
      "nano": 250000000
    },
    "dlongMin": {
      "units": 0,
      "nano": 134000000
    },
    "dshortMin": {
      "units": 0,
      "nano": 118000000
    },
    "shortEnabledFlag": true,
    "name": "Доллар США",
    "exchange": "FX",
    "nominal": {
      "currency": "usd",
      "units": 1,
      "nano": 0
    },
    "countryOfRisk": "",
    "countryOfRiskName": "",
    "tradingStatus": 1,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "isoCurrencyName": "usd",
    "minPriceIncrement": {
      "units": 0,
      "nano": 2500000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG0013HQ524",
    "ticker": "JPYRUB_TOM",
    "classCode": "CETS",
    "isin": "",
    "lot": 100000,
    "currency": "rub",
    "klong": {
      "units": 2,
      "nano": 0
    },
    "kshort": {
      "units": 2,
      "nano": 0
    },
    "dlong": {
      "units": 0,
      "nano": 991900000
    },
    "dshort": {
      "units": 2,
      "nano": 648100000
    },
    "dlongMin": {
      "units": 0,
      "nano": 910000000
    },
    "dshortMin": {
      "units": 0,
      "nano": 910000000
    },
    "shortEnabledFlag": false,
    "name": "Иена",
    "exchange": "FX",
    "nominal": {
      "currency": "jpy",
      "units": 100,
      "nano": 0
    },
    "countryOfRisk": "",
    "countryOfRiskName": "",
    "tradingStatus": 1,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "isoCurrencyName": "jpy",
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG0013HQ5K4",
    "ticker": "CHFRUB_TOM",
    "classCode": "CETS",
    "isin": "",
    "lot": 1000,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "Швейцарский франк",
    "exchange": "FX",
    "nominal": {
      "currency": "chf",
      "units": 1,
      "nano": 0
    },
    "countryOfRisk": "",
    "countryOfRiskName": "",
    "tradingStatus": 1,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "isoCurrencyName": "chf",
    "minPriceIncrement": {
      "units": 0,
      "nano": 2500000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG0013HQ5F0",
    "ticker": "GBPRUB_TOM",
    "classCode": "CETS",
    "isin": "",
    "lot": 1000,
    "currency": "rub",
    "klong": {
      "units": 2,
      "nano": 0
    },
    "kshort": {
      "units": 2,
      "nano": 0
    },
    "dlong": {
      "units": 0,
      "nano": 991900000
    },
    "dshort": {
      "units": 2,
      "nano": 648100000
    },
    "dlongMin": {
      "units": 0,
      "nano": 910000000
    },
    "dshortMin": {
      "units": 0,
      "nano": 910000000
    },
    "shortEnabledFlag": false,
    "name": "Фунт стерлингов",
    "exchange": "FX",
    "nominal": {
      "currency": "gbp",
      "units": 1,
      "nano": 0
    },
    "countryOfRisk": "",
    "countryOfRiskName": "",
    "tradingStatus": 1,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "isoCurrencyName": "gbp",
    "minPriceIncrement": {
      "units": 0,
      "nano": 2500000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG333333333",
    "ticker": "TMOS",
    "classCode": "TQTF",
    "isin": "RU000A101X76",
    "lot": 1,
    "currency": "rub",
    "klong": {
      "units": 2,
      "nano": 0
    },
    "kshort": {
      "units": 2,
      "nano": 0
    },
    "dlong": {
      "units": 0,
      "nano": 640000000
    },
    "dshort": {
      "units": 0,
      "nano": 960000000
    },
    "dlongMin": {
      "units": 0,
      "nano": 400000000
    },
    "dshortMin": {
      "units": 0,
      "nano": 400000000
    },
    "shortEnabledFlag": false,
    "name": "Тинькофф iMOEX",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2020-07-13T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "",
    "rebalancingFreq": "quarterly",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 2000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG005DXDPK9",
    "ticker": "FXGD",
    "classCode": "TQTF",
    "isin": "IE00B8XB7377",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "FinEx Золото",
    "exchange": "MOEX_PLUS",
    "focusType": "mixed_allocation",
    "releasedDate": "2013-10-17T00:00:00.000Z",
    "numShares": {
      "units": 1738450,
      "nano": 0
    },
    "countryOfRisk": "",
    "countryOfRiskName": "",
    "sector": "materials",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG00PVNWQ15",
    "ticker": "VTBE",
    "classCode": "TQTD",
    "isin": "RU000A100HQ5",
    "lot": 10,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "РСХБ – Фонд Акций развивающихся стран",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2019-06-27T00:00:00.000Z",
    "countryOfRisk": "",
    "countryOfRiskName": "",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 1000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG000T1G7X6",
    "ticker": "SCZ",
    "classCode": "SPBXM",
    "isin": "US4642882736",
    "lot": 1,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "iShares MSCI EAFE Small-Cap ETF",
    "exchange": "SPB",
    "focusType": "equity",
    "countryOfRisk": "US",
    "countryOfRiskName": "Соединенные Штаты Америки",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 1,
    "otcFlag": false,
    "buyAvailableFlag": false,
    "sellAvailableFlag": false,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG00RPRPBY4",
    "ticker": "VTBU",
    "classCode": "TQTD",
    "isin": "RU000A101368",
    "lot": 10,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "РСХБ – Корп еврооблигации РФ",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2019-11-19T00:00:00.000Z",
    "countryOfRisk": "",
    "countryOfRiskName": "",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 1000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A104172",
    "ticker": "RU000A104172",
    "classCode": "TQIF",
    "isin": "RU000A104172",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "ЗПИФ ПАРУС-Сберлог",
    "exchange": "MOEX",
    "focusType": "equity",
    "releasedDate": "2021-08-17T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "financial",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A104B87",
    "ticker": "SBBE",
    "classCode": "TQTF",
    "isin": "RU000A104B87",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "Первая - Блокчейн Экономика",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2021-12-20T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "financial",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 1000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG00YM3BX27",
    "ticker": "AKCH",
    "classCode": "TQTF",
    "isin": "RU000A102FK8",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "Альфа-Капитал Китайские Акции",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2020-11-30T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 20000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG00M8C8Y03",
    "ticker": "FXKZ",
    "classCode": "TQTF",
    "isin": "IE00BG0C3K84",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "FinEx Акции казахстанских компаний",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2018-10-16T00:00:00.000Z",
    "numShares": {
      "units": 1800000,
      "nano": 0
    },
    "countryOfRisk": "KZ",
    "countryOfRiskName": "Республика Казахстан",
    "sector": "other",
    "rebalancingFreq": "quarterly",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG011C8HRT6",
    "ticker": "SBRS",
    "classCode": "TQTF",
    "isin": "RU000A1035Q2",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "Сбер - Осторожный смарт фонд",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2021-05-24T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 1000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG005HLSZ23",
    "ticker": "FXUS",
    "classCode": "TQTF",
    "isin": "IE00BD3QHZ91",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "FinEx Акции американских компаний",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2013-10-31T00:00:00.000Z",
    "numShares": {
      "units": 330000,
      "nano": 0
    },
    "countryOfRisk": "US",
    "countryOfRiskName": "Соединенные Штаты Америки",
    "sector": "other",
    "rebalancingFreq": "quarterly",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG01526SWY3",
    "ticker": "FXBC",
    "classCode": "TQTF",
    "isin": "IE000GBF7ZU3",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "FinEx Экосистема Блокчейн",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "countryOfRisk": "IE",
    "countryOfRiskName": "",
    "sector": "",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG0073DLHS1",
    "ticker": "FXRL",
    "classCode": "TQTF",
    "isin": "IE00BQ1Y6480",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "FinEx Акции российских компаний",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2016-03-02T00:00:00.000Z",
    "numShares": {
      "units": 250000,
      "nano": 0
    },
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "quarterly",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 5000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG011C8J9N0",
    "ticker": "SBCS",
    "classCode": "TQTF",
    "isin": "RU000A1035N9",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "Сбер - Консервативный смарт фонд",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2021-05-24T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 1000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG013T81ZQ6",
    "ticker": "FXEM",
    "classCode": "TQTF",
    "isin": "IE0003KBK0Z6",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "FinEx Развивающиеся страны без Китая и Индии",
    "exchange": "MOEX",
    "focusType": "equity",
    "countryOfRisk": "IE",
    "countryOfRiskName": "",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG004HNZFH2",
    "ticker": "FXRB",
    "classCode": "TQTF",
    "isin": "IE00B7L7CP77",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "FinEx Еврооблигации рос. компаний (RUB)",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2013-04-30T00:00:00.000Z",
    "numShares": {
      "units": 580543,
      "nano": 0
    },
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "semi_annual",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 1000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG00MF4JRQ8",
    "ticker": "VTBB",
    "classCode": "TQTF",
    "isin": "RU000A1002S8",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "ВТБ Корпоративные облигации",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2019-01-31T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 20000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG000Q1MZ15",
    "ticker": "SPSB",
    "classCode": "SPBXM",
    "isin": "US78464A4748",
    "lot": 1,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "SPDR Portfolio Short Term Corporate Bond ETF",
    "exchange": "SPB",
    "focusType": "equity",
    "releasedDate": "2009-12-17T00:00:00.000Z",
    "numShares": {
      "units": 166400000,
      "nano": 0
    },
    "countryOfRisk": "US",
    "countryOfRiskName": "Соединенные Штаты Америки",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 1,
    "otcFlag": false,
    "buyAvailableFlag": false,
    "sellAvailableFlag": false,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A102YC6",
    "ticker": "TSPV",
    "classCode": "TQTD",
    "isin": "RU000A102YC6",
    "lot": 100,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "Тинькофф SPAC",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2021-04-01T00:00:00.000Z",
    "countryOfRisk": "US",
    "countryOfRiskName": "Соединенные Штаты Америки",
    "sector": "financial",
    "rebalancingFreq": "quarterly",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG00M0C8YM7",
    "ticker": "SBMX",
    "classCode": "TQTF",
    "isin": "RU000A0ZZH92",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "Сбер Индекс Мосбиржи",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2018-08-15T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 1000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A102XZ9",
    "ticker": "AMEM",
    "classCode": "TQTF",
    "isin": "RU000A102XZ9",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "АТОН Рынки возможностей",
    "exchange": "MOEX",
    "focusType": "equity",
    "releasedDate": "2021-03-25T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A102XX4",
    "ticker": "AMRE",
    "classCode": "TQTF",
    "isin": "RU000A102XX4",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "АТОН Российские акции +",
    "exchange": "MOEX",
    "focusType": "equity",
    "releasedDate": "2021-03-25T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A102XW6",
    "ticker": "AMCC",
    "classCode": "TQTF",
    "isin": "RU000A102XW6",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "АТОН Облачные технологии",
    "exchange": "MOEX",
    "focusType": "equity",
    "releasedDate": "2021-03-25T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "it",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A102XY2",
    "ticker": "AMRB",
    "classCode": "TQTF",
    "isin": "RU000A102XY2",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "АТОН Российские облигации +",
    "exchange": "MOEX",
    "focusType": "equity",
    "releasedDate": "2021-03-25T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A102XV8",
    "ticker": "AMVF",
    "classCode": "TQTF",
    "isin": "RU000A102XV8",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "АТОН Недооцененные компании США",
    "exchange": "MOEX",
    "focusType": "equity",
    "releasedDate": "2021-03-25T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A102XS4",
    "ticker": "AMMF",
    "classCode": "TQTF",
    "isin": "RU000A102XS4",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "АТОН  Лидеры роста США",
    "exchange": "MOEX",
    "focusType": "equity",
    "releasedDate": "2021-03-25T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A102XU0",
    "ticker": "AMIG",
    "classCode": "TQTF",
    "isin": "RU000A102XU0",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "АТОН Надежные облигации",
    "exchange": "MOEX",
    "focusType": "equity",
    "releasedDate": "2021-03-25T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A102XT2",
    "ticker": "AMHC",
    "classCode": "TQTF",
    "isin": "RU000A102XT2",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "АТОН Медицина и биотех США",
    "exchange": "MOEX",
    "focusType": "equity",
    "releasedDate": "2021-03-25T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "health_care",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A101EJ5",
    "ticker": "VTBX",
    "classCode": "TQTF",
    "isin": "RU000A101EJ5",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "ВТБ Индекс Мосбиржи",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2020-02-10T00:00:00.000Z",
    "countryOfRisk": "",
    "countryOfRiskName": "",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 50000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A102Y25",
    "ticker": "AMLV",
    "classCode": "TQTF",
    "isin": "RU000A102Y25",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "АТОН  Тихая гавань",
    "exchange": "MOEX",
    "focusType": "equity",
    "releasedDate": "2021-03-25T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A102XQ8",
    "ticker": "AMGM",
    "classCode": "TQTF",
    "isin": "RU000A102XQ8",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "АТОН Золотодобытчики",
    "exchange": "MOEX",
    "focusType": "equity",
    "releasedDate": "2021-03-25T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A102Y33",
    "ticker": "AMSC",
    "classCode": "TQTF",
    "isin": "RU000A102Y33",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "АТОН Цифровое будущее",
    "exchange": "MOEX",
    "focusType": "equity",
    "releasedDate": "2021-03-25T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "it",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A102XR6",
    "ticker": "AMIN",
    "classCode": "TQTF",
    "isin": "RU000A102XR6",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "АТОН Инновации",
    "exchange": "MOEX",
    "focusType": "equity",
    "releasedDate": "2021-03-25T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "it",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG00P5M77Y0",
    "ticker": "AKSP",
    "classCode": "TQTD",
    "isin": "RU000A1006V3",
    "lot": 1,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "Альфа-Капитал S&P 500",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2019-03-19T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A102Y09",
    "ticker": "AMSL",
    "classCode": "TQTF",
    "isin": "RU000A102Y09",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "АТОН Серебро",
    "exchange": "MOEX",
    "focusType": "equity",
    "releasedDate": "2021-03-25T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A102XP0",
    "ticker": "AMHY",
    "classCode": "TQTF",
    "isin": "RU000A102XP0",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "АТОН Доходные облигации мира",
    "exchange": "MOEX",
    "focusType": "equity",
    "releasedDate": "2021-03-25T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A1039P6",
    "ticker": "TGRN",
    "classCode": "TQTD",
    "isin": "RU000A1039P6",
    "lot": 100,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "Тинькофф Green Economy",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2021-06-10T00:00:00.000Z",
    "countryOfRisk": "WD",
    "countryOfRiskName": "Весь мир",
    "sector": "energy",
    "rebalancingFreq": "quarterly",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A102Y17",
    "ticker": "AMGF",
    "classCode": "TQTF",
    "isin": "RU000A102Y17",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "АТОН Ставка на рост",
    "exchange": "MOEX",
    "focusType": "equity",
    "releasedDate": "2021-03-25T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "it",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A1039N1",
    "ticker": "TBRU",
    "classCode": "TQTF",
    "isin": "RU000A1039N1",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "Тинькофф Bonds RUB",
    "exchange": "MOEX_PLUS",
    "focusType": "fixed_income",
    "releasedDate": "2021-06-10T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "quarterly",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 1000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A102XN5",
    "ticker": "AMGR",
    "classCode": "TQTF",
    "isin": "RU000A102XN5",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "АТОН Генетическая революция",
    "exchange": "MOEX",
    "focusType": "equity",
    "releasedDate": "2021-03-25T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "health_care",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG00RPRPX12",
    "ticker": "VTBM",
    "classCode": "TQTF",
    "isin": "RU000A1014L8",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "ВТБ Ликвидность",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2019-11-28T00:00:00.000Z",
    "countryOfRisk": "",
    "countryOfRiskName": "",
    "sector": "government",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG013RTHWK8",
    "ticker": "SBHI",
    "classCode": "TQTF",
    "isin": "RU000A103ZQ1",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "Первая - Халяльные инвестиции",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2021-11-02T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 2000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG011MM3NT8",
    "ticker": "AKMD",
    "classCode": "TQTF",
    "isin": "RU000A1036A4",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "Альфа-Капитал Медицина",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2021-05-27T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "health_care",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 20000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG00NNQMD85",
    "ticker": "AKNX",
    "classCode": "TQTD",
    "isin": "RU000A0ZZTQ4",
    "lot": 1,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "Альфа-Капитал Технологии 100",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2018-11-13T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "financial",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG00ZXX3KF9",
    "ticker": "FXFA",
    "classCode": "TQTF",
    "isin": "IE00BMDKNN44",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "FinEx Облигаций развитых рынков",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "countryOfRisk": "",
    "countryOfRiskName": "",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG014M8NBM4",
    "ticker": "AKGD",
    "classCode": "TQTF",
    "isin": "RU000A1045N8",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "Альфа-Капитал Золото",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2021-11-25T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A102EQ8",
    "ticker": "TSPX",
    "classCode": "TQTD",
    "isin": "RU000A102EQ8",
    "lot": 100,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "Тинькофф S&P 500",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2020-11-23T00:00:00.000Z",
    "countryOfRisk": "US",
    "countryOfRiskName": "Соединенные Штаты Америки",
    "sector": "",
    "rebalancingFreq": "quarterly",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG011C8JMM2",
    "ticker": "SBPS",
    "classCode": "TQTF",
    "isin": "RU000A1035R0",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "Сбер - Прогрессивный смарт фонд",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2021-05-24T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 2000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG005HLTYH9",
    "ticker": "FXIT",
    "classCode": "TQTF",
    "isin": "IE00BD3QJ757",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "FinEx Акции компаний IT-сектора США",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2013-10-31T00:00:00.000Z",
    "numShares": {
      "units": 692000,
      "nano": 0
    },
    "countryOfRisk": "US",
    "countryOfRiskName": "Соединенные Штаты Америки",
    "sector": "it",
    "rebalancingFreq": "quarterly",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 1,
      "nano": 0
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG000BK58Q1",
    "ticker": "EWP",
    "classCode": "SPBXM",
    "isin": "US4642867646",
    "lot": 1,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "iShares MSCI Spain ETF",
    "exchange": "SPB",
    "focusType": "equity",
    "releasedDate": "1996-03-18T00:00:00.000Z",
    "numShares": {
      "units": 30075000,
      "nano": 0
    },
    "countryOfRisk": "ES",
    "countryOfRiskName": "Королевство Испания",
    "sector": "other",
    "rebalancingFreq": "quarterly",
    "tradingStatus": 1,
    "otcFlag": false,
    "buyAvailableFlag": false,
    "sellAvailableFlag": false,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A100P44",
    "ticker": "SBRB",
    "classCode": "TQTF",
    "isin": "RU000A100P44",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "Сбер Рублевые Корп Облигации",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2019-07-25T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 1000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS0BMDKNM37",
    "ticker": "FXDM",
    "classCode": "TQTF",
    "isin": "IE00BMDKNM37",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "FinEx Акции компаний развитых стран без США",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "countryOfRisk": "IE",
    "countryOfRiskName": "",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A102EM7",
    "ticker": "TIPO",
    "classCode": "TQTD",
    "isin": "RU000A102EM7",
    "lot": 100,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "Тинькофф Индекс IPO",
    "exchange": "MOEX_WEEKEND",
    "focusType": "equity",
    "releasedDate": "2020-11-23T00:00:00.000Z",
    "countryOfRisk": "US",
    "countryOfRiskName": "Соединенные Штаты Америки",
    "sector": "",
    "rebalancingFreq": "quarterly",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A102EK1",
    "ticker": "TBIO",
    "classCode": "TQTD",
    "isin": "RU000A102EK1",
    "lot": 100,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "Тинькофф NASDAQ Biotech",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2020-11-23T00:00:00.000Z",
    "countryOfRisk": "US",
    "countryOfRiskName": "Соединенные Штаты Америки",
    "sector": "health_care",
    "rebalancingFreq": "quarterly",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG013RTJNG1",
    "ticker": "AKVG",
    "classCode": "TQTF",
    "isin": "RU000A103ZD9",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "Альфа-Капитал Видеоигры",
    "exchange": "MOEX_MORNING",
    "focusType": "equity",
    "releasedDate": "2021-10-28T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 20000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG012T4JCQ9",
    "ticker": "AKSC",
    "classCode": "TQTF",
    "isin": "RU000A103L86",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "Альфа-Капитал Космос",
    "exchange": "MOEX_MORNING",
    "focusType": "equity",
    "releasedDate": "2021-08-19T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 20000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG00NB6KGN0",
    "ticker": "SBCB",
    "classCode": "TQTD",
    "isin": "RU000A1000Q6",
    "lot": 1,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "Первая - Фонд Российские еврооблигации",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2018-12-28T00:00:00.000Z",
    "countryOfRisk": "",
    "countryOfRiskName": "",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG013RTJSX1",
    "ticker": "AKEB",
    "classCode": "TQTF",
    "isin": "RU000A103ZC1",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "Альфа-Капитал Управляемые еврооблигации",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2021-10-28T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 50000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A1022Z1",
    "ticker": "RU000A1022Z1",
    "classCode": "TQIF",
    "isin": "RU000A1022Z1",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "ЗПИФ ПАРУС-ОЗН",
    "exchange": "MOEX",
    "focusType": "equity",
    "releasedDate": "2020-07-09T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "financial",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 1,
      "nano": 0
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG00PVNWFM6",
    "ticker": "VTBH",
    "classCode": "TQTD",
    "isin": "RU000A100HP7",
    "lot": 10,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "РСХБ – Корп облигации США",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2019-06-27T00:00:00.000Z",
    "countryOfRisk": "",
    "countryOfRiskName": "",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 1000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG005VKB7D7",
    "ticker": "FXCN",
    "classCode": "TQTF",
    "isin": "IE00BD3QFB18",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "FinEx Акции китайских компаний",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2014-02-06T00:00:00.000Z",
    "numShares": {
      "units": 300000,
      "nano": 0
    },
    "countryOfRisk": "CN",
    "countryOfRiskName": "Китайская Народная Республика",
    "sector": "other",
    "rebalancingFreq": "quarterly",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 500000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A103VN7",
    "ticker": "TCBR",
    "classCode": "TQTD",
    "isin": "RU000A103VN7",
    "lot": 100,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "Тинькофф CyberSecurity",
    "exchange": "MOEX_WEEKEND",
    "focusType": "equity",
    "releasedDate": "2021-10-04T00:00:00.000Z",
    "countryOfRisk": "WD",
    "countryOfRiskName": "Весь мир",
    "sector": "it",
    "rebalancingFreq": "annual",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A103VL1",
    "ticker": "TBUY",
    "classCode": "TQTD",
    "isin": "RU000A103VL1",
    "lot": 100,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "Тинькофф BuyBack Leaders",
    "exchange": "MOEX_WEEKEND",
    "focusType": "equity",
    "releasedDate": "2021-10-04T00:00:00.000Z",
    "countryOfRisk": "US",
    "countryOfRiskName": "Соединенные Штаты Америки",
    "sector": "other",
    "rebalancingFreq": "quarterly",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG00V9V16J8",
    "ticker": "VTBG",
    "classCode": "TQTF",
    "isin": "RU000A101NZ2",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "ВТБ Фонд Золото",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2020-05-14T00:00:00.000Z",
    "countryOfRisk": "",
    "countryOfRiskName": "",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG000000000",
    "ticker": "TUSD",
    "classCode": "TQTD",
    "isin": "RU000A1011S9",
    "lot": 100,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "Тинькофф Вечный портфель USD",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2019-11-07T00:00:00.000Z",
    "countryOfRisk": "US",
    "countryOfRiskName": "Соединенные Штаты Америки",
    "sector": "",
    "rebalancingFreq": "quarterly",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG000000002",
    "ticker": "TEUR",
    "classCode": "TQTE",
    "isin": "RU000A1011T7",
    "lot": 100,
    "currency": "eur",
    "shortEnabledFlag": false,
    "name": "Тинькофф Вечный портфель EUR",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2019-11-07T00:00:00.000Z",
    "countryOfRisk": "EU",
    "countryOfRiskName": "Еврозона",
    "sector": "",
    "rebalancingFreq": "quarterly",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG000000001",
    "ticker": "TRUR",
    "classCode": "TQTF",
    "isin": "RU000A1011U5",
    "lot": 1,
    "currency": "rub",
    "klong": {
      "units": 2,
      "nano": 0
    },
    "kshort": {
      "units": 2,
      "nano": 0
    },
    "dlong": {
      "units": 0,
      "nano": 375900000
    },
    "dshort": {
      "units": 0,
      "nano": 464100000
    },
    "dlongMin": {
      "units": 0,
      "nano": 210000000
    },
    "dshortMin": {
      "units": 0,
      "nano": 210000000
    },
    "shortEnabledFlag": false,
    "name": "Тинькофф Вечный портфель RUB",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2019-11-07T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "",
    "rebalancingFreq": "quarterly",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A103VM9",
    "ticker": "TSST",
    "classCode": "TQTD",
    "isin": "RU000A103VM9",
    "lot": 100,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "Тинькофф ESG Leaders",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2021-10-04T00:00:00.000Z",
    "countryOfRisk": "WD",
    "countryOfRiskName": "Весь мир",
    "sector": "other",
    "rebalancingFreq": "annual",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG111111111",
    "ticker": "TECH",
    "classCode": "TQTD",
    "isin": "RU000A101X68",
    "lot": 100,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "Тинькофф NASDAQ",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2020-07-13T00:00:00.000Z",
    "countryOfRisk": "US",
    "countryOfRiskName": "Соединенные Штаты Америки",
    "sector": "it",
    "rebalancingFreq": "quarterly",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG01236BLK6",
    "ticker": "FXRD",
    "classCode": "TQTF",
    "isin": "IE000CK9ZWC0",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "FinEx Облигации с рублевыми дивидендами",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "countryOfRisk": "IE",
    "countryOfRiskName": "",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG000BPNZB6",
    "ticker": "IYT",
    "classCode": "SPBXM",
    "isin": "US4642871929",
    "lot": 1,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "iShares US Transportation ETF",
    "exchange": "SPB",
    "focusType": "equity",
    "countryOfRisk": "US",
    "countryOfRiskName": "Соединенные Штаты Америки",
    "sector": "industrials",
    "rebalancingFreq": "",
    "tradingStatus": 1,
    "otcFlag": false,
    "buyAvailableFlag": false,
    "sellAvailableFlag": false,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG011C7ZVQ2",
    "ticker": "FXIP",
    "classCode": "TQTF",
    "isin": "IE00096YBNR3",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "FinEx Облигации TIPS (RUB, хедж)",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "countryOfRisk": "IE",
    "countryOfRiskName": "",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG0151LJYV0",
    "ticker": "AKSF",
    "classCode": "TQTF",
    "isin": "RU000A104CU0",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "Альфа-Капитал Стратегия будущего",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2021-12-27T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A103VJ5",
    "ticker": "TEMS",
    "classCode": "TQTD",
    "isin": "RU000A103VJ5",
    "lot": 100,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "Тинькофф Emerging Markets",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2021-10-04T00:00:00.000Z",
    "countryOfRisk": "WD",
    "countryOfRiskName": "Весь мир",
    "sector": "other",
    "rebalancingFreq": "annual",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A103VK3",
    "ticker": "TPAS",
    "classCode": "TQTD",
    "isin": "RU000A103VK3",
    "lot": 100,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "Тинькофф PAN-ASIA",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2021-10-04T00:00:00.000Z",
    "countryOfRisk": "AA",
    "countryOfRiskName": "Азия",
    "sector": "other",
    "rebalancingFreq": "annual",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A103VH9",
    "ticker": "TFNX",
    "classCode": "TQTD",
    "isin": "RU000A103VH9",
    "lot": 100,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "Тинькофф FinTech",
    "exchange": "MOEX_WEEKEND",
    "focusType": "equity",
    "releasedDate": "2021-10-04T00:00:00.000Z",
    "countryOfRisk": "WD",
    "countryOfRiskName": "Весь мир",
    "sector": "other",
    "rebalancingFreq": "annual",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A103VF3",
    "ticker": "TSOX",
    "classCode": "TQTD",
    "isin": "RU000A103VF3",
    "lot": 100,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "Тинькофф Semiconductors",
    "exchange": "MOEX_MORNING",
    "focusType": "equity",
    "releasedDate": "2021-10-04T00:00:00.000Z",
    "countryOfRisk": "WD",
    "countryOfRiskName": "Весь мир",
    "sector": "it",
    "rebalancingFreq": "quarterly",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A103VG1",
    "ticker": "TRAI",
    "classCode": "TQTD",
    "isin": "RU000A103VG1",
    "lot": 100,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "Тинькофф AI-Robotics",
    "exchange": "MOEX_MORNING",
    "focusType": "equity",
    "releasedDate": "2021-10-04T00:00:00.000Z",
    "countryOfRisk": "WD",
    "countryOfRiskName": "Весь мир",
    "sector": "it",
    "rebalancingFreq": "quarterly",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A103VE6",
    "ticker": "TEUS",
    "classCode": "TQTE",
    "isin": "RU000A103VE6",
    "lot": 100,
    "currency": "eur",
    "shortEnabledFlag": false,
    "name": "Тинькофф Eurostocks 50",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2021-10-04T00:00:00.000Z",
    "countryOfRisk": "EU",
    "countryOfRiskName": "Еврозона",
    "sector": "other",
    "rebalancingFreq": "annual",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG005N1KZX4",
    "ticker": "FXRU",
    "classCode": "TQTF",
    "isin": "IE00BD5FH213",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "FinEx Еврооблигации рос. компаний (USD)",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2013-02-25T00:00:00.000Z",
    "numShares": {
      "units": 4122320,
      "nano": 0
    },
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "semi_annual",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG011Q55QS3",
    "ticker": "FXES",
    "classCode": "TQTF",
    "isin": "IE00BNYK7W79",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "FinEx Видеоигры и Киберспорт",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "countryOfRisk": "IE",
    "countryOfRiskName": "",
    "sector": "it",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG000BK2V65",
    "ticker": "EWI",
    "classCode": "SPBXM",
    "isin": "US46434G8309",
    "lot": 1,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "iShares MSCI Italy ETF",
    "exchange": "SPB",
    "focusType": "equity",
    "releasedDate": "1996-03-18T00:00:00.000Z",
    "numShares": {
      "units": 14100000,
      "nano": 0
    },
    "countryOfRisk": "IT",
    "countryOfRiskName": "Итальянская Республика",
    "sector": "other",
    "rebalancingFreq": "quarterly",
    "tradingStatus": 1,
    "otcFlag": false,
    "buyAvailableFlag": false,
    "sellAvailableFlag": false,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG012VJJFG7",
    "ticker": "AKQU",
    "classCode": "TQTD",
    "isin": "RU000A103NR5",
    "lot": 1,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "Альфа-Капитал Квант",
    "exchange": "MOEX_MORNING",
    "focusType": "equity",
    "releasedDate": "2021-09-06T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS0BNYK7X86",
    "ticker": "FXTP",
    "classCode": "TQTF",
    "isin": "IE00BNYK7X86",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "FinEx Облигации TIPS",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "countryOfRisk": "IE",
    "countryOfRiskName": "",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG00PGVPH30",
    "ticker": "VTBA",
    "classCode": "TQTD",
    "isin": "RU000A100E21",
    "lot": 10,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "РСХБ - Акции компаний США",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2019-05-28T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 1000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG013N16YX7",
    "ticker": "FXRE",
    "classCode": "TQTF",
    "isin": "IE0000CHPRB9",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "FinEx Фонды недвижимости REIT",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "countryOfRisk": "IE",
    "countryOfRiskName": "",
    "sector": "real_estate",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG00R980XY3",
    "ticker": "FXRW",
    "classCode": "TQTF",
    "isin": "IE00BK224M36",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "FinEx Акции глобального рынка",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "countryOfRisk": "EU",
    "countryOfRiskName": "Еврозона",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG00NJ6XQ74",
    "ticker": "SBGB",
    "classCode": "TQTF",
    "isin": "RU000A1000F9",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "Первая - ОФЗ",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2018-12-24T00:00:00.000Z",
    "countryOfRisk": "",
    "countryOfRiskName": "",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 1000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG011C8G9X2",
    "ticker": "SBDS",
    "classCode": "TQTF",
    "isin": "RU000A1035L3",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "Первая - Динамичный Смарт фонд",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2021-05-24T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 2000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG006GYFHV6",
    "ticker": "FXMM",
    "classCode": "TQTF",
    "isin": "IE00BL3DYX33",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "FinEx Казначейские облигации США",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2014-05-16T00:00:00.000Z",
    "numShares": {
      "units": 840000,
      "nano": 0
    },
    "countryOfRisk": "US",
    "countryOfRiskName": "Соединенные Штаты Америки",
    "sector": "government",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG00R9805F5",
    "ticker": "FXWO",
    "classCode": "TQTF",
    "isin": "IE00BK224L29",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "FinEx Акции глобального рынка",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "countryOfRisk": "EU",
    "countryOfRiskName": "Еврозона",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG00D7BBRR8",
    "ticker": "ESGD",
    "classCode": "SPBXM",
    "isin": "US46435G5163",
    "lot": 1,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "iShares ESG Aware MSCI EAFE ETF",
    "exchange": "SPB",
    "focusType": "equity",
    "countryOfRisk": "WD",
    "countryOfRiskName": "Весь мир",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 1,
    "otcFlag": false,
    "buyAvailableFlag": false,
    "sellAvailableFlag": false,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A103TD2",
    "ticker": "TBEU",
    "classCode": "TQTE",
    "isin": "RU000A103TD2",
    "lot": 100,
    "currency": "eur",
    "shortEnabledFlag": false,
    "name": "Тинькофф Еврооблигации EUR",
    "exchange": "MOEX_PLUS",
    "focusType": "fixed_income",
    "releasedDate": "2021-09-27T00:00:00.000Z",
    "countryOfRisk": "WD",
    "countryOfRiskName": "Весь мир",
    "sector": "other",
    "rebalancingFreq": "semi_annual",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG00Y6D0N45",
    "ticker": "FXIM",
    "classCode": "TQTD",
    "isin": "IE00BNC2D728",
    "lot": 10,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "FinEx Акции компаний IT-сектора США",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "countryOfRisk": "IE",
    "countryOfRiskName": "",
    "sector": "it",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 1000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG00NTZWLM4",
    "ticker": "SBSP",
    "classCode": "TQTF",
    "isin": "RU000A1006W1",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "Сбер S&P 500",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2019-03-19T00:00:00.000Z",
    "countryOfRisk": "US",
    "countryOfRiskName": "Соединенные Штаты Америки",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 200000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG005H7MXN2",
    "ticker": "FXDE",
    "classCode": "TQTF",
    "isin": "IE00BD3QJN10",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "FinEx Акции немецких компаний",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2013-10-31T00:00:00.000Z",
    "numShares": {
      "units": 280000,
      "nano": 0
    },
    "countryOfRisk": "DE",
    "countryOfRiskName": "Федеративная Республика Германия",
    "sector": "other",
    "rebalancingFreq": "quarterly",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 5000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "TCS00A1030P5",
    "ticker": "AMDG",
    "classCode": "TQTF",
    "isin": "RU000A1030P5",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "АТОН  Дивиденды",
    "exchange": "MOEX",
    "focusType": "equity",
    "releasedDate": "2021-04-12T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG222222222",
    "ticker": "TGLD",
    "classCode": "TQTD",
    "isin": "RU000A101X50",
    "lot": 100,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "Тинькофф Золото",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2020-07-13T00:00:00.000Z",
    "countryOfRisk": "WD",
    "countryOfRiskName": "Весь мир",
    "sector": "",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG000BXV152",
    "ticker": "IEV",
    "classCode": "SPBXM",
    "isin": "US4642878619",
    "lot": 1,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "iShares Europe ETF",
    "exchange": "SPB",
    "focusType": "equity",
    "countryOfRisk": "EU",
    "countryOfRiskName": "Еврозона",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 1,
    "otcFlag": false,
    "buyAvailableFlag": false,
    "sellAvailableFlag": false,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG00YRW4B42",
    "ticker": "AKME",
    "classCode": "TQTF",
    "isin": "RU000A102E78",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "Альфа-Капитал Управляемые Российские Акции",
    "exchange": "MOEX",
    "focusType": "equity",
    "releasedDate": "2020-11-23T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 20000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG00V7649K4",
    "ticker": "AKMB",
    "classCode": "TQTF",
    "isin": "RU000A101PN3",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "Альфа-Капитал Управляемые облигации",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2020-05-19T00:00:00.000Z",
    "countryOfRisk": "",
    "countryOfRiskName": "",
    "sector": "municipal",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 100000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG0027F1TD5",
    "ticker": "KBWB",
    "classCode": "SPBXM",
    "isin": "US46138E6288",
    "lot": 1,
    "currency": "usd",
    "shortEnabledFlag": false,
    "name": "Invesco KBW Bank ETF",
    "exchange": "SPB",
    "focusType": "equity",
    "releasedDate": "2007-06-12T20:00:00.000Z",
    "countryOfRisk": "US",
    "countryOfRiskName": "Соединенные Штаты Америки",
    "sector": "financial",
    "rebalancingFreq": "quarterly",
    "tradingStatus": 1,
    "otcFlag": false,
    "buyAvailableFlag": false,
    "sellAvailableFlag": false,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG00Q3HQJ74",
    "ticker": "AKEU",
    "classCode": "TQTE",
    "isin": "RU000A100Q43",
    "lot": 1,
    "currency": "eur",
    "shortEnabledFlag": false,
    "name": "Альфа-Капитал Европа 600",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2019-08-08T00:00:00.000Z",
    "countryOfRisk": "",
    "countryOfRiskName": "",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG00NRFC2X2",
    "ticker": "FXTB",
    "classCode": "TQTF",
    "isin": "IE00BL3DYW26",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "FinEx Казначейские облигации США (USD)",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2019-04-10T00:00:00.000Z",
    "numShares": {
      "units": 571000,
      "nano": 0
    },
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  },
  {
    "figi": "BBG011C8J503",
    "ticker": "SBWS",
    "classCode": "TQTF",
    "isin": "RU000A1035S8",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "Сбер - Взвешенный смарт фонд",
    "exchange": "MOEX_PLUS",
    "focusType": "equity",
    "releasedDate": "2021-05-24T00:00:00.000Z",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "other",
    "rebalancingFreq": "",
    "tradingStatus": 4,
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": 0,
      "nano": 2000000
    },
    "apiTradeAvailableFlag": true,
    "uid": ""
  }
]
